namespace PatternsApp.Template
{
    public class GenerateReport : Task
    {
        public GenerateReport(IAuditTrail auditTrail) : base(auditTrail)
        {
            logData = "Report generated by: Lilly, Time: 14:55";
        }
        protected override void doExecute()
        {
            Console.WriteLine("Generating report...");
        }
    }

}